f1/f1/model.sdf

This is in reference to issue #17 
The topic names in the sdf file need to be corrected.

Minor Updates to F1 model

---

amazon_robot/amazon_robot_bringup/amazon_robot_gazebo_spawner/amazon_robot_gazebo_spawner/amazon_robot_gazebo_spawner.py
amazon_robot/amazon_robot_bringup/bringup/launch/amazon_robot_in_aws_world.py
amazon_robot/amazon_robot_bringup/bringup/launch/aws_amazon_robot_multiple.py
amazon_robot/amazon_robot_bringup/bringup/launch/follow_target_action_client.py
amazon_robot/amazon_robot_bringup/bringup/launch/multi_tb3_simulation_launch.py
amazon_robot/amazon_robot_bringup/bringup/launch/spawn_tb3_launch.py
amazon_robot/amazon_robot_bringup/bringup/params/nav2_multirobot_params_1_with_control.yaml
amazon_robot/amazon_robot_bringup/bringup/params/nav2_multirobot_params_2_with_control.yaml
amazon_robot/amazon_robot_bringup/bringup/params/nav2_params_with_control.yaml
amazon_robot/amazon_robot_bringup/bringup/rviz/amazon_robot_namespaced_view.rviz
amazon_robot/amazon_robot_controller/include/amazon_robot_controller/plugins/action/load_pallet.hpp
amazon_robot/amazon_robot_controller/include/amazon_robot_controller/robot_controller.hpp
amazon_robot/amazon_robot_controller/plugins/action/load_pallet.cpp
amazon_robot/amazon_robot_controller/src/robot_controller.cpp
amazon_robot/amazon_robot_gazebo/models/amazon_robot2/model.sdf
amazon_robot/exercise/multi-robot.py
amazon_robot/start_simulation.sh

Solves #22 
TODO: Restructuring of branches

Working branch for Amazon Warehouse MultiRobot Scenario

---

f1/simple_circuit/model.sdf

fixed error in model name

---

README.md

how to contribute section added

---

README.md

added links in branches

---

f1/f1_renault_laser/model.sdf

This is in reference to issue #41

Update path of model file

---

f1/launch/many_curves.launch
f1/launch/montmelo_line.launch
f1/launch/montreal_line.launch
f1/launch/nurburgring_line.launch
f1/launch/simple_circuit.launch

use_sim_time variable value updated for launchs

---

f1/launch/simple_circuit.launch

Update simple circuit world in launch

---

f1/worlds/simple_circuit.world
f1/worlds/simple_circuit_black.world

Camera position corrected

---

amazon_robot/amazon_robot_bringup/bringup/params/nav2_params_with_control.yaml
amazon_robot/amazon_robot_controller/behavior_trees/follow_waypoints_and_load.xml

The following edits were made:
1. Modified follow_waypoints_and_load.xml BT navigator in amazon_robot_controller.
2. Added corresponding plugin libraries to nav2_params_with_control.yaml in amazon_robot_bringup
Steps to test: Follow the steps mentioned in Issue #93 
---
Solves Issues: 
-  #93
- TheRoboticsClub/gsoc2021-Siddharth_Saha#12
- TheRoboticsClub/gsoc2021-Siddharth_Saha#13

Fixed Behavior Tree in Amazon warehouse package

---

montecarlo_visual_loc/models/house_mcvl/model.config
montecarlo_visual_loc/models/house_mcvl/model.sdf

Add textures for the visual montecarlo loc

---

power_tower_inspection/models/rust_defect_01/model.sdf
power_tower_inspection/models/rust_defect_02/model.sdf
power_tower_inspection/models/rust_defect_03/model.sdf

Rotated rust defect models

---

turtlebot2/Readme.md
turtlebot2/turtlebot2/launch/empty_world.launch.py
turtlebot2/turtlebot2/launch/spawn_model.launch.py
turtlebot2/turtlebot2/rviz/turtlebot2_rviz.rviz

* Adding input arguments to spawn_model.launch.py
* Changing structure

Fixes in turtlebot2

---

amazon_hospital/hospital_world/src/person.cpp
amazon_hospital/hospital_world/worlds/hospital_follow_person.world

I have integrated everything required in this issue: #166 :
* Initial camera position and fullscreen mode in gazebo world
* Disabling auto movement of the model person (plugin)

[foxy] Small changes hospital world package

---

mountain_car/car/model.config
mountain_car/car/model.sdf
mountain_car/thin_road.world

updating car and world files to implement easy mountain car scenario in RL-Studio 0.1.0

solving issue-120

---

roomba_robot/models/roombaROS_cam/roombaROS_cam/model.sdf

Added camera to the roomba vacuum based on the Turtlebot2 model, the camera is facing up.

Changed model.sdf

---

scripts/instructions.json
scripts/manager.py

Credits to @Bhardwaj-Himanshu, see issue in [RoboticsAcademy#1904](https://github.com/JdeRobot/RoboticsAcademy/issues/1904)

Removed unused gazebo_path

---

scripts/.env
scripts/.rosinstall
scripts/Dockerfile.pre-base
scripts/instructions.json
scripts/manager.py

From https://github.com/JdeRobot/RoboticsAcademy/pull/2058

Rotors dependencies removed

---

scripts/.env

Updated paths
Added newmanager exercise paths
Removed catkin_ws, PX4 and STDR paths 
#280

[Humble].env updated to latest paths

---

jderobot_drones/jderobot_drones/drone_wrapper.py
jderobot_drones/launch/as2_default_classic_gazebo.launch.py

Removal of aerostack2 behaviours

---

CustomRobots/drone_assets/models/boat_beacon/boat_beacon.sdf

[Humble] Removes PX4 takeoff failures

---

scripts/.env
scripts/entrypoint.sh

https://github.com/JdeRobot/RoboticsAcademy/issues/2253

Solves no module found error

---

scripts/.env

- Removed custom robots paths that no longer exist 
- Removed export display

[Humble] .env file updated

---

jderobot_drones/jderobot_drones/drone_wrapper.py

Fixes https://github.com/JdeRobot/RoboticsAcademy/issues/2302

[Humble] Typecasting yaw variables to float before calling aerostack APIs

---

CustomRobots/Turtlebot2/turtlebot2_simulated/turtlebot2/launch/spawn_model.launch.py
Launchers/follow_person.launch.py

This solves the issues mentioned in #366

Paused gazebo parameter and delay to ensure proper spawn

---

Worlds/hospital_follow_person.world
Worlds/montmelo_line_ackermann_followingcam.world

Support for moving objects in the world using ros2 services
